# stage3/strings/BUILD
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "strings",
    srcs = ["strings.cc"],
    hdrs = ["strings.h"],
    visibility = ["//visibility:public"],
)
